name: CI

on: [push, pull_request]

jobs:
  deviantart:
    name: >-
      deviantart ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        ruby: [ '3.1', '3.0', 2.7, 2.6, 2.5 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: |
          gem install bundler --no-document
          bundle install
      - name: Rake test
        run:  bundle exec rake test
